# Workload specification for developer platform backend
# Drives both subscription vending and workload resource provisioning

apiVersion: platform/v1
kind: PostgresBackend

metadata:
  name: myapp

spec:
  environment: dev         # dev | staging | prod
  workloadType: Production # Production | DevTest (subscription offer type)

  # Platform config (typically set by the platform team or in a shared config)
  managementGroupId: 'initno-sandboxes'
  ownerPrincipalId: '48e4cd26-7979-43ab-8086-0b6b819ffd00'

  # Optional resource overrides (defaults shown)
  postgresVersion: "16"
  computeTier: Burstable   # Burstable | GeneralPurpose | MemoryOptimized
  storageSizeGb: 32
